/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/public/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check (unauthenticated) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                            /** Format: date-time */
                            ts?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/payment-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payment intents */
        get: operations["listPaymentIntents"];
        put?: never;
        /** Create a payment intent */
        post: operations["createPaymentIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/payment-intents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Retrieve a payment intent */
        get: operations["retrievePaymentIntent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/payment-intents/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a payment intent */
        post: operations["cancelPaymentIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/payment-intents/{id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** List transaction legs contributing to this intent */
        get: operations["listPaymentIntentTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/payment-intents/{id}/routing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** List router candidates evaluated for this intent (chosen + rejected) */
        get: operations["listPaymentIntentRoutingCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/checkout/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Public read-only checkout view (no auth). Used by hosted checkout + polling clients. */
        get: operations["getCheckoutView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/refunds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List refunds */
        get: operations["listRefunds"];
        put?: never;
        /** Create a refund */
        post: operations["createRefund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/refunds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Retrieve a refund */
        get: operations["retrieveRefund"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/refunds/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry a refund (optionally to a different address)
         * @description Requeue a refund that is `failed`, `retry_scheduled` or `pending` for an
         *     immediate dispatch attempt. Supply `destination` to redirect the refund to a
         *     different address than the one on file — e.g. the original payer address
         *     bounced, cannot receive the settlement asset, or the customer supplied a new
         *     wallet. Refunds in a terminal state (`succeeded`, `cancelled`) return 409.
         */
        post: operations["retryRefund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/refunds/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Payer-facing refund status (unauthenticated, safe view)
         * @description Public, unauthenticated status endpoint safe to expose in customer emails
         *     and receipts. Destination address is redacted to the last 6 characters;
         *     no merchant PII is returned.
         */
        get: operations["refundStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/payouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payouts */
        get: operations["listPayouts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/payouts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Retrieve a payout */
        get: operations["retrievePayout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/payouts/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Requeue a failed payout for another dispatch attempt */
        post: operations["replayPayout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/webhook-endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhook endpoints */
        get: operations["listWebhookEndpoints"];
        put?: never;
        /** Create a webhook endpoint */
        post: operations["createWebhookEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/webhook-endpoints/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Retrieve a webhook endpoint */
        get: operations["retrieveWebhookEndpoint"];
        put?: never;
        post?: never;
        /** Delete a webhook endpoint */
        delete: operations["deleteWebhookEndpoint"];
        options?: never;
        head?: never;
        /** Update a webhook endpoint */
        patch: operations["updateWebhookEndpoint"];
        trace?: never;
    };
    "/api/public/v1/webhook-endpoints/{id}/rotate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the signing secret. Previous secret remains valid for 24h. */
        post: operations["rotateWebhookEndpointSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/v1/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List supported tokens (unauthenticated) */
        get: operations["listTokens"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error?: string;
            code?: string;
            details?: {
                [key: string]: unknown;
            };
        };
        PaymentIntent: {
            /** Format: uuid */
            id?: string;
            amount?: string;
            currency?: string;
            /** @enum {string} */
            mode?: "test" | "live";
            /** @enum {string} */
            status?: "created" | "requires_payment" | "quoted" | "awaiting_signature" | "executing" | "partially_filled" | "settled" | "failed" | "expired" | "cancelled" | "refunded";
            /** Format: uri */
            checkout_url?: string;
            /**
             * @description Settlement chain. One of: robinhood, solana, ethereum, base, arbitrum, optimism, polygon, bnb, avalanche.
             * @enum {string}
             */
            settlement_chain?: "robinhood" | "solana" | "ethereum" | "base" | "arbitrum" | "optimism" | "polygon" | "bnb" | "avalanche";
            settlement_token?: string;
            settlement_address?: string;
            customer_email?: string | null;
            /** Format: date-time */
            expires_at?: string;
            /** Format: date-time */
            created_at?: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        RouteCandidate: {
            id?: string;
            /** @description lifi-default | lifi-cctp | jupiter-direct | ... */
            provider?: string;
            chosen?: boolean;
            ai_pick?: boolean;
            score?: number;
            from_chain?: string;
            to_chain?: string;
            from_token?: string;
            to_token?: string;
            to_amount_usd?: number;
            fee_usd?: number;
            gas_usd?: number;
            duration_sec?: number;
            reason?: string | null;
            error?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        Refund: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            payment_intent_id?: string;
            amount_usd?: number;
            chain?: string;
            token?: string;
            destination?: string;
            reason?: string;
            /** @enum {string} */
            status?: "pending" | "paid" | "failed" | "cancelled";
            tx_hash?: string | null;
            /** Format: date-time */
            created_at?: string;
            paid_at?: string | null;
        };
        Payout: {
            /** Format: uuid */
            id?: string;
            payment_intent_id?: string | null;
            rail?: string;
            destination?: string;
            chain?: string;
            token?: string;
            amount?: string;
            currency?: string;
            /** @enum {string} */
            status?: "queued" | "pending" | "processing" | "pending_provider" | "retry_scheduled" | "paid" | "failed" | "paused";
            tx_hash?: string | null;
            failure_reason?: string | null;
            attempts?: number;
            next_attempt_at?: string | null;
            paid_at?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        WebhookEndpoint: {
            /** Format: uuid */
            id?: string;
            /** Format: uri */
            url?: string;
            events?: string[];
            enabled?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** @description Signing secret. Returned only in create + rotate-secret responses. Store immediately. */
            secret?: string;
        };
        Token: {
            chain?: string;
            address?: string;
            symbol?: string;
            name?: string;
            decimals?: number;
            verified?: boolean;
        };
        CheckoutView: {
            /** Format: uuid */
            id?: string;
            amount?: string;
            currency?: string;
            status?: string;
            settlement_chain?: string;
            settlement_token?: string;
            /** Format: date-time */
            expires_at?: string;
            legs?: {
                chain?: string;
                token?: string;
                amount_usd?: number;
                status?: string;
            }[];
        };
    };
    responses: never;
    parameters: {
        /** @description Safe-retry key. Replays within 24h return the original response; same key + different body returns 409. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPaymentIntents: {
        parameters: {
            query?: {
                limit?: number;
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["PaymentIntent"][];
                    };
                };
            };
        };
    };
    createPaymentIntent: {
        parameters: {
            query?: never;
            header?: {
                /** @description Safe-retry key. Replays within 24h return the original response; same key + different body returns 409. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    amount: number;
                    /** @default USD */
                    currency?: string;
                    /**
                     * @description Settlement chain. One of: robinhood, solana, ethereum, base, arbitrum, optimism, polygon, bnb, avalanche.
                     * @enum {string}
                     */
                    settlement_chain?: "robinhood" | "solana" | "ethereum" | "base" | "arbitrum" | "optimism" | "polygon" | "bnb" | "avalanche";
                    settlement_token?: string;
                    settlement_address?: string;
                    /** Format: email */
                    customer_email?: string;
                    expires_in_seconds?: number;
                    metadata?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentIntent"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Idempotency key mismatch */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retrievePaymentIntent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentIntent"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelPaymentIntent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentIntent"];
                };
            };
            /** @description Cannot cancel in current status */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPaymentIntentTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
    };
    listPaymentIntentRoutingCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["RouteCandidate"][];
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCheckoutView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutView"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRefunds: {
        parameters: {
            query?: {
                payment_intent_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Refund"][];
                    };
                };
            };
        };
    };
    createRefund: {
        parameters: {
            query?: never;
            header?: {
                /** @description Safe-retry key. Replays within 24h return the original response; same key + different body returns 409. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description Payment intent to refund. Must be settled or partially funded.
                     */
                    intent_id: string;
                    /** @description Refund amount in USD. Capped by the intent's refundable balance. */
                    amount_usd: number;
                    /** @description Optional payer address to refund to. If omitted, the refund waits in `pending` with `failure_reason: missing_destination` until the merchant supplies one from the dashboard. */
                    destination?: string;
                    /** @example customer_request */
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refund"];
                };
            };
            /** @description Intent not settled */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refund exceeds refundable balance */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retrieveRefund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refund"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retryRefund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description New destination address. Omit to retry to the address already on the refund. */
                    destination?: string;
                    /** @example address_bounced */
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Retry dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        retried?: boolean;
                        refund?: components["schemas"]["Refund"];
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refund is not in a retryable status */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No destination on file and none supplied */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refundStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                        /** Format: uuid */
                        payment_intent_id?: string;
                        amount_usd?: number;
                        chain?: string | null;
                        token?: string | null;
                        /** @description e.g. '…a1b2c3' */
                        destination_tail?: string;
                        reason?: string;
                        /** @enum {string} */
                        status?: "pending" | "processing" | "retry_scheduled" | "succeeded" | "failed" | "cancelled";
                        tx_hash?: string | null;
                        failure_reason?: string | null;
                        attempts?: number;
                        /** Format: date-time */
                        created_at?: string;
                        /** Format: date-time */
                        updated_at?: string;
                        /** Format: date-time */
                        paid_at?: string | null;
                        terminal?: boolean;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPayouts: {
        parameters: {
            query?: {
                status?: string;
                payment_intent_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Payout"][];
                    };
                };
            };
        };
    };
    retrievePayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payout"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replayPayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requeued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payout"];
                };
            };
            /** @description Payout is not in a replayable state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listWebhookEndpoints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["WebhookEndpoint"][];
                    };
                };
            };
        };
    };
    createWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    url: string;
                    events: string[];
                    /** @default true */
                    enabled?: boolean;
                };
            };
        };
        responses: {
            /** @description Created — response includes plaintext `secret`; store immediately. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpoint"];
                };
            };
        };
    };
    retrieveWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpoint"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: uri */
                    url?: string;
                    events?: string[];
                    enabled?: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpoint"];
                };
            };
        };
    };
    rotateWebhookEndpointSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK — new plaintext `secret` returned once. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpoint"];
                };
            };
        };
    };
    listTokens: {
        parameters: {
            query?: {
                chain?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Token"][];
                    };
                };
            };
        };
    };
}
